name: omarl2
channels:
  - menpo
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - cloudpickle=3.1.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - elfutils=0.192
  - ffmpeg=4.4.2
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glew=2.1.0
  - glfw3=3.2.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - gym=0.21.0
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - intel-openmp=2022.0.1
  - jinja2=3.1.4
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libarchive=3.7.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcurl=8.10.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgl=1.7.0
  - libglu=9.0.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.3
  - libmicrohttpd=1.0.1
  - libnghttp2=1.64.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libpciaccess=0.18
  - libpng=1.6.44
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.13.4
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.5
  - mesalib=24.2.6
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.1
  - numpy=1.22.1
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - p11-kit=0.24.1
  - pillow=10.4.0
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.8.12
  - python_abi=3.8
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.3.0
  - sqlite=3.47.0
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tk=8.6.13
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.20.0
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wheel=0.45.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-glproto=1.4.17
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.11
  - xorg-libxxf86vm=1.1.5
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - bootstrapped==0.0.2
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.37
      - decorator==4.4.2
      - dm-control==0.0.408319720
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.3.0
      - fasteners==0.19
      - fonttools==4.54.1
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - h5py==3.11.0
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lxml==5.3.0
      - matplotlib==3.7.5
      - mjrl==1.0.0
      - moviepy==1.0.3
      - mujoco==3.2.3
      - mujoco-py==2.1.2.14
      - nop==0.1.1
      - packaging==24.2
      - pandas==2.0.3
      - patchelf==0.17.2.1
      - pip==24.0
      - platformdirs==4.3.6
      - proglog==0.1.10
      - protobuf==5.28.3
      - psutil==6.1.0
      - pybullet==3.2.6
      - pyopengl==3.1.7
      - pyparsing==2.4.7
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - readchar==4.2.1
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - submitit==1.5.2
      - termcolor==2.4.0
      - tqdm==4.67.0
      - tzdata==2024.2
      - wandb==0.18.6
      - zipp==3.20.2
